language: python

sudo: false

python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5

env:
    - DJANGO=Django==1.7.8
    - DJANGO=Django==1.8.4

matrix:
    exclude:
        - python: 3.5
          env: DJANGO=Django==1.7.8

before_install:
    - pip install codecov

install:
    - pip install $DJANGO django-oscar==1.1.1
    - pip install -r requirements.testing.txt
    - pip install .

script:
    - coverage run ./runtests.py

after_success:
    - codecov
