language: python

sudo: false

python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5

env:
    matrix:
        - DJANGO=Django==1.7.8
        - DJANGO=Django==1.8.4
        - OSCAR=django-oscar==1.1.1

install:
    - pip install $DJANGO $OSCAR
    - pip install -r requirements.testing.txt
    - pip install .

script:
    - coverage run ./runtests.py

after_success:
    - coveralls
